baseURL = 'https://new.ayton-village.org'
languageCode = 'en-gb'
disableHugoGeneratorInject = true
title = 'Ayton Village'
disableKinds = ['taxonomy', 'taxonomyTerm']
summaryLength = 25
[markup.goldmark.renderer]
unsafe = true
[module]
[[module.mounts]]
source = '../common/layouts'
target = 'layouts'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = '../common/scss'
target = 'assets/scss'
