[build]
publish = "public"
command = "hugo --minify --environment=production"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ./ ../common/"

[build.environment]
HUGO_VERSION = "0.122.0"

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[headers]]
  for = "/*/*.*.*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''
